CREATE TABLE [dbo].[DIM_CURSO_IES_TESTE] (
    [CD_IES]              INT           NOT NULL,
    [DSC_IES]             VARCHAR (50)  NOT NULL,
    [CD_UNI_ORGANICA]     INT           NULL,
    [DSC_UNI_ORGANICA]    VARCHAR (100) NULL,
    [DSC_TIPO_ENSINO]     VARCHAR (100) NULL,
    [DSC_NUTS2]           VARCHAR (50)  NULL,
    [DSC_NUTS3]           VARCHAR (50)  NULL,
    [DSC_DISTRITO]        VARCHAR (100) NULL,
    [DSC_CONCELHO]        VARCHAR (100) NULL,
    [CD_IES_CURSO]        INT           NULL,
    [CD_CURSO]            INT           NULL,
    [DSC_CURSO]           VARCHAR (150) NULL,
    [DSC_NIVEL_ENSINO]    VARCHAR (100) NULL,
    [V_ECTS]              INT           NULL,
    [DSC_DURACAO]         VARCHAR (100) NULL,
    [DSC_CONCURSO]        VARCHAR (100) NULL,
    [DSC_PROVAS_INGRESSO] VARCHAR (200) NULL,
    [URL_CURSO]           VARCHAR (250) NULL,
    [CD_CITEF_1D]         INT           NULL,
    [DSC_CITEF_1D]        VARCHAR (100) NULL,
    [CD_CITEF_2D]         INT           NULL,
    [DSC_CITEF_2D]        VARCHAR (100) NULL,
    [CD_CITEF_3D]         INT           NULL,
    [DSC_CITEF_3D]        VARCHAR (100) NULL,
    [CD_AREA_FORMACAO]    INT           NULL,
    [DSC_AREA_FORMACAO]   VARCHAR (100) NULL,
    [V_VAGAS_1F]          INT           NULL,
    [V_VAGAS_2F]          INT           NULL,
    [V_NOTA_MEDIA_1F]     FLOAT (53)    NULL,
    [V_NOTA_MEDIA_2F]     FLOAT (53)    NULL,
    [V_NOTA_ULT_COL_1F]   FLOAT (53)    NULL,
    [V_NOTA_ULT_COL_2F]   FLOAT (53)    NULL,
    [URL_ESTATISTICAS]    VARCHAR (250) NULL,
    [URL_AVALIACAO]       VARCHAR (250) NULL
);

