CREATE TABLE [dbo].[DIM_NIVEL_ENSINO] (
    [ID_DIM_NIVEL_ENSINO] INT          IDENTITY (1, 1) NOT NULL,
    [DSC_NIVEL_ENSINO]    VARCHAR (50) NULL,
    CONSTRAINT [PK_DIM_NIVEL_ENSINO] PRIMARY KEY CLUSTERED ([ID_DIM_NIVEL_ENSINO] ASC)
);

