CREATE TABLE [dbo].[DIM_PROFISSAO_BF] (
    [ID_DIM_PROFISSAO_BF] INT           IDENTITY (1, 1) NOT NULL,
    [DSC_PROFISSAO_BF]    VARCHAR (300) NULL,
    CONSTRAINT [PK_PROFISSAO_BF] PRIMARY KEY CLUSTERED ([ID_DIM_PROFISSAO_BF] ASC)
);

