CREATE TABLE [dbo].[DIM_COMPETENCIA_BG_AGG] (
    [ID_DIM_COMPETENCIA_BG_AGG] INT           IDENTITY (1, 1) NOT NULL,
    [DSC_COMPETENCIA_BG_AGG]    VARCHAR (200) NULL,
    CONSTRAINT [PK_DIM_COMPETENCIA_BG_AGG] PRIMARY KEY CLUSTERED ([ID_DIM_COMPETENCIA_BG_AGG] ASC)
);

