CREATE TABLE [dbo].[DIM_COMPETENCIA_ONET_DET] (
    [ID_DIM_COMPETENCIA_ONET_DET] VARCHAR (50) NOT NULL,
    [DSC_COMPETENCIA_ONET_DET]    VARCHAR (50) NULL,
    CONSTRAINT [PK_COMPETENCIA_ONET_DET] PRIMARY KEY CLUSTERED ([ID_DIM_COMPETENCIA_ONET_DET] ASC)
);

