CREATE TABLE [dbo].[DIM_SECTOR_BF] (
    [ID_DIM_SECTOR_BF] INT          IDENTITY (1, 1) NOT NULL,
    [DSC_SECTOR_BF]    VARCHAR (50) NULL,
    CONSTRAINT [PK_DIM_SECTOR_BF] PRIMARY KEY CLUSTERED ([ID_DIM_SECTOR_BF] ASC)
);

