CREATE TABLE [dbo].[DIM_TIPO_CONTRATO] (
    [ID_DIM_TIPO_CONTRATO] INT          IDENTITY (1, 1) NOT NULL,
    [DSC_TIPO_CONTRATO]    VARCHAR (50) NULL,
    CONSTRAINT [PK_DIM_TIPO_CONTRATO] PRIMARY KEY CLUSTERED ([ID_DIM_TIPO_CONTRATO] ASC)
);

