CREATE TABLE [dbo].[DIM_SECTOR_INE] (
    [ID_DIM_SECTOR_INE] VARCHAR (5)   NOT NULL,
    [DSC_SECTOR_INE]    VARCHAR (100) NULL,
    CONSTRAINT [PK_DIM_SECTOR_INE] PRIMARY KEY CLUSTERED ([ID_DIM_SECTOR_INE] ASC)
);

