CREATE TABLE [dbo].[DIM_PROFISSAO_BF2] (
    [ID_DIM_PROFISSAO_BF2] INT           IDENTITY (1, 1) NOT NULL,
    [DSC_PROFISSAO_BF2]    VARCHAR (300) NULL,
    CONSTRAINT [PK_DIM_PROFISSAO_BF2] PRIMARY KEY CLUSTERED ([ID_DIM_PROFISSAO_BF2] ASC)
);

