CREATE TABLE [dbo].[DIM_API_INE_TIPO_CONTRATO] (
    [ID_DIM_API_INE_TIPO_CONTRATO]  VARCHAR (5)   NOT NULL,
    [DSC_DIM_API_INE_TIPO_CONTRATO] VARCHAR (200) NULL,
    CONSTRAINT [PK_DIM_API_INE_TIPO_CONTRATO] PRIMARY KEY CLUSTERED ([ID_DIM_API_INE_TIPO_CONTRATO] ASC)
);

