CREATE TABLE [dbo].[DIM_MEDIA_FINAL] (
    [ID_DIM_MEDIA_FINAL] INT          IDENTITY (1, 1) NOT NULL,
    [DSC_MEDIA_FINAL]    VARCHAR (50) NULL,
    CONSTRAINT [PK_DIM_MEDIA_FINAL] PRIMARY KEY CLUSTERED ([ID_DIM_MEDIA_FINAL] ASC)
);

