CREATE TABLE [dbo].[DIM_NIVEL_ENSINO_DGEEC] (
    [ID_DIM_NIVEL_ENSINO_DGEEC] INT          IDENTITY (1, 1) NOT NULL,
    [DSC_NIVEL_ENSINO_DGEEC]    VARCHAR (50) NULL,
    CONSTRAINT [PK_DIM_NIVEL_ENSINO_DGEEC] PRIMARY KEY CLUSTERED ([ID_DIM_NIVEL_ENSINO_DGEEC] ASC)
);

