CREATE TABLE [dbo].[DIM_NACIONALIDADE] (
    [ID_DIM_NACIONALIDADE] INT          IDENTITY (1, 1) NOT NULL,
    [DSC_NACIONALIDADE]    VARCHAR (50) NULL,
    CONSTRAINT [PK_DIM_NACIONALIDADE] PRIMARY KEY CLUSTERED ([ID_DIM_NACIONALIDADE] ASC)
);

