CREATE TABLE [dbo].[DIM_API_INE_SEXO] (
    [ID_DIM_API_INE_SEXO]  VARCHAR (5)   NOT NULL,
    [DSC_DIM_API_INE_SEXO] VARCHAR (200) NULL,
    CONSTRAINT [PK_DIM_API_INE_SEXO] PRIMARY KEY CLUSTERED ([ID_DIM_API_INE_SEXO] ASC)
);

