CREATE TABLE [dbo].[DIM_COMPETENCIA_BG_DET] (
    [ID_DIM_COMPETENCIA_BG_DET] INT          IDENTITY (1, 1) NOT NULL,
    [DSC_COMPETENCIA_BG_DET]    VARCHAR (50) NULL,
    CONSTRAINT [PK_DIM_COMPETENCIA_BG_DET] PRIMARY KEY CLUSTERED ([ID_DIM_COMPETENCIA_BG_DET] ASC)
);

