CREATE TABLE [dbo].[DIM_COMPETENCIA_ONET_AGG] (
    [ID_DIM_COMPETENCIA_ONET_AGG] VARCHAR (5)   NOT NULL,
    [DSC_COMPETENCIA_ONET_AGG]    VARCHAR (200) NULL,
    CONSTRAINT [PK_DIM_COMPETENCIA_ONET_AGG] PRIMARY KEY CLUSTERED ([ID_DIM_COMPETENCIA_ONET_AGG] ASC)
);

