CREATE TABLE [dbo].[DIM_API_INE_SECTOR] (
    [ID_DIM_API_INE_SECTOR]  VARCHAR (50)  NOT NULL,
    [DSC_DIM_API_INE_SECTOR] VARCHAR (500) NULL,
    CONSTRAINT [PK_DIM_API_INE_SECTOR] PRIMARY KEY CLUSTERED ([ID_DIM_API_INE_SECTOR] ASC)
);

