CREATE TABLE [dbo].[DIM_API_INE_REGIME_TRAB] (
    [ID_DIM_API_INE_REGIME_TRAB]  VARCHAR (50)  NOT NULL,
    [DSC_DIM_API_INE_REGIME_TRAB] VARCHAR (500) NULL,
    CONSTRAINT [PK_DIM_API_INE_REGIME_TRAB] PRIMARY KEY CLUSTERED ([ID_DIM_API_INE_REGIME_TRAB] ASC)
);

