CREATE TABLE [dbo].[DIM_SEXO] (
    [ID_DIM_SEXO] INT          IDENTITY (1, 1) NOT NULL,
    [DSC_SEXO]    VARCHAR (10) NULL,
    CONSTRAINT [PK_DIM_SEXO] PRIMARY KEY CLUSTERED ([ID_DIM_SEXO] ASC)
);

