CREATE TABLE [dbo].[DIM_IES_CURSO] (
    [ID_DIM_IES_CURSO] INT          IDENTITY (1, 1) NOT NULL,
    [DSC_IES_CURSO]    VARCHAR (50) NULL,
    CONSTRAINT [PK_DIM_IES_CURSO] PRIMARY KEY CLUSTERED ([ID_DIM_IES_CURSO] ASC)
);

