CREATE TABLE [dbo].[DIM_DIMENSAO_EMP] (
    [ID_DIM_DIMENSAO_EMP] INT          IDENTITY (1, 1) NOT NULL,
    [DSC_DIMENSAO_EMP]    VARCHAR (50) NULL,
    CONSTRAINT [PK_DIM_DIMENSAO_EMP] PRIMARY KEY CLUSTERED ([ID_DIM_DIMENSAO_EMP] ASC)
);

