CREATE TABLE [dbo].[DIM_API_INE_NIVEL_ENSINO] (
    [ID_DIM_API_INE_NIVEL_ENSINO]  VARCHAR (50)  NOT NULL,
    [DSC_DIM_API_INE_NIVEL_ENSINO] VARCHAR (500) NULL,
    CONSTRAINT [PK_DIM_API_INE_NIVEL_ENSINO] PRIMARY KEY CLUSTERED ([ID_DIM_API_INE_NIVEL_ENSINO] ASC)
);

