CREATE TABLE [dbo].[DIM_AREA_FORMACAO] (
    [ID_DIM_AREA_FORMACAO] INT           IDENTITY (1, 1) NOT NULL,
    [DSC_AREA_FORMACAO]    VARCHAR (500) NULL,
    CONSTRAINT [PK_DIM_AREA_FORMACAO] PRIMARY KEY CLUSTERED ([ID_DIM_AREA_FORMACAO] ASC)
);

