CREATE TABLE [dbo].[DIM_API_INE_IDADE_TRABALHO] (
    [ID_DIM_API_INE_IDADE_TRABALHO]  VARCHAR (5)   NOT NULL,
    [DSC_DIM_API_INE_IDADE_TRABALHO] VARCHAR (200) NULL,
    CONSTRAINT [PK_DIM_API_INE_IDADE_TRABALHO] PRIMARY KEY CLUSTERED ([ID_DIM_API_INE_IDADE_TRABALHO] ASC)
);

