CREATE TABLE [dbo].[DIM_SEXO_INE] (
    [ID_DIM_SEXO_INE]  VARCHAR (5)  NOT NULL,
    [DSC_DIM_SEXO_INE] VARCHAR (50) NULL,
    CONSTRAINT [PK_DIM_SEXO_INE] PRIMARY KEY CLUSTERED ([ID_DIM_SEXO_INE] ASC)
);

