CREATE TABLE [dbo].[DIM_SIT_PROFISSIONAL] (
    [ID_DIM_SIT_PROFISSIONAL] INT          IDENTITY (1, 1) NOT NULL,
    [DSC_SIT_PROFISSIONAL]    VARCHAR (50) NULL,
    CONSTRAINT [PK_DIM_SIT_PROFISSIONAL] PRIMARY KEY CLUSTERED ([ID_DIM_SIT_PROFISSIONAL] ASC)
);

