CREATE TABLE [dbo].[DIM_FORMA_INGRESSO] (
    [ID_DIM_FORMA_INGRESSO] INT           IDENTITY (1, 1) NOT NULL,
    [DSC_FORMA_INGRESSO]    VARCHAR (200) NULL,
    CONSTRAINT [PK_DIM_FORMA_INGRESSO] PRIMARY KEY CLUSTERED ([ID_DIM_FORMA_INGRESSO] ASC)
);

