CREATE TABLE [dbo].[DIM_IDADE_TRABALHO] (
    [ID_DIM_IDADE_TRABALHO] INT          IDENTITY (1, 1) NOT NULL,
    [DSC_IDADE_TRABALHO]    VARCHAR (20) NULL,
    CONSTRAINT [PK_DIM_IDADE_TRABALHO] PRIMARY KEY CLUSTERED ([ID_DIM_IDADE_TRABALHO] ASC)
);

