CREATE TABLE [dbo].[ETL_FILE_INSTANCES] (
    [ID_ETL_FLE_INSTANCES] BIGINT         IDENTITY (1, 1) NOT NULL,
    [FILE_KEY]             NVARCHAR (50)  NOT NULL,
    [FILE_NAME]            NVARCHAR (200) NOT NULL,
    [FILE_TYPE]            NVARCHAR (50)  NOT NULL,
    [ID_FILE_STATUS]       INT            CONSTRAINT [DF_ETL_FILE_INSTANCES_STATUS] DEFAULT ((0)) NOT NULL,
    [CREATE_DATE]          DATETIME       CONSTRAINT [DF_ETL_FILE_INSTANCES_CREATE_DATE] DEFAULT (getdate()) NOT NULL,
    [ACCEPTED_DATE]        DATETIME       NULL,
    [PROCESSED_DATE]       DATETIME       NULL,
    CONSTRAINT [PK_ETL_FILE_INSTANCES] PRIMARY KEY CLUSTERED ([ID_ETL_FLE_INSTANCES] ASC)
);

