CREATE TABLE [dbo].[ETL_FILE_STATUS] (
    [ID_ETL_FILE_STATUS] INT            NOT NULL,
    [FILE_STATUS_DESC]   NVARCHAR (200) NOT NULL,
    CONSTRAINT [PK_ETL_FILE_STATUS] PRIMARY KEY CLUSTERED ([ID_ETL_FILE_STATUS] ASC)
);

