CREATE TABLE [dbo].[FCT_KPI] (
    [ID_FCT_KPI] INT        IDENTITY (1, 1) NOT NULL,
    [ID_DIM_KPI] INT        NULL,
    [ID_DIM_VAL] INT        NULL,
    [VAL_KPI]    FLOAT (53) NULL,
    [DT_INSERT]  DATETIME   CONSTRAINT [DF_FCT_KPI_DT_INSERT] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_FCT_KPI] PRIMARY KEY CLUSTERED ([ID_FCT_KPI] ASC)
);

