CREATE TABLE [dbo].[FCT_KPI_TRIMESTRE] (
    [ID_FCT_KPI_TRIMESTRE] INT         IDENTITY (1, 1) NOT NULL,
    [ID_DIM_KPI]           INT         NULL,
    [ID_DIM_VAL]           INT         NULL,
    [CD_ANO_TRIMESTRE]     VARCHAR (6) NULL,
    [VAL_KPI]              FLOAT (53)  NULL,
    [DT_INSERT]            DATETIME    CONSTRAINT [DF_FCT_KPI_TRIMESTRE_DT_INSERT] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_FCT_KPI_TRIMESTRE] PRIMARY KEY CLUSTERED ([ID_FCT_KPI_TRIMESTRE] ASC)
);

