CREATE TABLE [dbo].[FCT_KPI_ANO] (
    [ID_FCT_KPI_ANO] INT        IDENTITY (1, 1) NOT NULL,
    [ID_DIM_KPI]     INT        NULL,
    [ID_DIM_VAL]     INT        NULL,
    [CD_ANO]         INT        NULL,
    [VAL_KPI]        FLOAT (53) NULL,
    [DT_INSERT]      DATETIME   CONSTRAINT [DF_FCT_KPI_ANO_DT_INSERT] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_FCT_KPI_ANO] PRIMARY KEY CLUSTERED ([ID_FCT_KPI_ANO] ASC) WITH (DATA_COMPRESSION = PAGE)
);

