CREATE TABLE [dbo].[WC_AREA_FORMACAO] (
    [ID_AREA_FORM] NVARCHAR (10)  NOT NULL,
    [V_CARD_1]     NVARCHAR (500) NOT NULL,
    [A_CARD_1]     NVARCHAR (500) NOT NULL,
    [V_CARD_2]     NVARCHAR (500) NOT NULL,
    [A_CARD_2]     NVARCHAR (500) NOT NULL,
    [V_CARD_3]     NVARCHAR (500) NOT NULL,
    [A_CARD_3]     NVARCHAR (500) NOT NULL,
    [V_CARD_4]     NVARCHAR (500) NOT NULL,
    [A_CARD_4]     NVARCHAR (500) NOT NULL,
    [V_CARD_5]     NVARCHAR (500) NOT NULL
);

