CREATE TABLE [dbo].[WC_CURSOS] (
    [ID_IES_CURSO] NVARCHAR (10)  NULL,
    [V_CARD_1]     NVARCHAR (500) NULL,
    [V_CARD_2]     NVARCHAR (500) NULL,
    [V_CARD_3]     NVARCHAR (500) NULL,
    [A_CARD_3]     NVARCHAR (500) NULL,
    [V_CARD_4]     NVARCHAR (500) NULL,
    [A_CARD_4]     NVARCHAR (500) NULL,
    [V_CARD_5]     NVARCHAR (500) NULL,
    [V_CARD_6]     NVARCHAR (500) NULL,
    [A_CARD_6]     NVARCHAR (500) NULL
);

