CREATE TABLE [dbo].[WC_COMP_BG] (
    [ID_BG]      NVARCHAR (10)  NULL,
    [V_CARD_1]   NVARCHAR (500) NULL,
    [V_CARD_2_1] NVARCHAR (500) NULL,
    [V_CARD_2_2] NVARCHAR (500) NULL,
    [V_CARD_3]   NVARCHAR (500) NULL
);

