CREATE TABLE [stg].[tbl_O_IES_CURSO] (
    [id]                           BIGINT          IDENTITY (1, 1) NOT NULL,
    [FileKey]                      NVARCHAR (50)   NOT NULL,
    [FileName]                     NVARCHAR (200)  NOT NULL,
    [estabelecimento_cod]          NVARCHAR (2000) NULL,
    [estabelecimento]              NVARCHAR (2000) NULL,
    [unidade_organica_cod]         NVARCHAR (2000) NULL,
    [unidade_organica]             NVARCHAR (2000) NULL,
    [tipo_ensino]                  NVARCHAR (2000) NULL,
    [natureza_ensino]              NVARCHAR (2000) NULL,
    [subsistema_ensino]            NVARCHAR (2000) NULL,
    [nuts_ii]                      NVARCHAR (2000) NULL,
    [nuts_iii_rev2013]             NVARCHAR (2000) NULL,
    [distrito]                     NVARCHAR (2000) NULL,
    [concelho]                     NVARCHAR (2000) NULL,
    [ies_curso]                    NVARCHAR (2000) NULL,
    [curso_cod]                    NVARCHAR (2000) NULL,
    [curso]                        NVARCHAR (2000) NULL,
    [nivel_ensino_dgeec]           NVARCHAR (2000) NULL,
    [ects]                         NVARCHAR (2000) NULL,
    [duracao]                      NVARCHAR (2000) NULL,
    [concurso]                     NVARCHAR (2000) NULL,
    [pre_requisitos]               NVARCHAR (2000) NULL,
    [vagas]                        NVARCHAR (2000) NULL,
    [vagas_label]                  NVARCHAR (2000) NULL,
    [provas_ingresso]              NVARCHAR (2000) NULL,
    [nota_ultimo_cont_geral]       NVARCHAR (2000) NULL,
    [nota_ultimo_cont_geral_label] NVARCHAR (2000) NULL,
    [media_colocados]              NVARCHAR (2000) NULL,
    [min_nota_concurso]            NVARCHAR (2000) NULL,
    [min_nota_prova_ingresso]      NVARCHAR (2000) NULL,
    [peso_notas_secund]            NVARCHAR (2000) NULL,
    [peso_notas_provas_ing]        NVARCHAR (2000) NULL,
    [url]                          NVARCHAR (2000) NULL,
    [CITEF2013_1d_cod]             NVARCHAR (2000) NULL,
    [CITEF2013_1d]                 NVARCHAR (2000) NULL,
    [CITEF2013_2d_cod]             NVARCHAR (2000) NULL,
    [CITEF2013_2d]                 NVARCHAR (2000) NULL,
    [CITEF2013_3d_cod]             NVARCHAR (2000) NULL,
    [CITEF2013_3d]                 NVARCHAR (2000) NULL,
    [area_formacao_cod]            NVARCHAR (2000) NULL,
    [area_formacao]                NVARCHAR (2000) NULL,
    [asset]                        NVARCHAR (2000) NULL,
    [propinas]                     NVARCHAR (2000) NULL,
    [descricao]                    NVARCHAR (2000) NULL,
    [morada]                       NVARCHAR (2000) NULL,
    [telefone]                     NVARCHAR (2000) NULL,
    [regime]                       NVARCHAR (2000) NULL,
    [visual_inscritos]             NVARCHAR (2000) NULL,
    [visual_diplomados]            NVARCHAR (2000) NULL,
    [visual_desemprego]            NVARCHAR (2000) NULL,
    [visual_vagas]                 NVARCHAR (2000) NULL,
    CONSTRAINT [PK_tbl_O_IES_CURSO] PRIMARY KEY CLUSTERED ([id] ASC)
);

