
CREATE   VIEW [dbo].[VW_DIM_SECTOR_BF] AS 
SELECT ID_DIM_SECTOR_BF
	, SETOR_1D
	, DSC_SECTOR_BF
	, SETOR_1D_DESIGNACAO
	, SETOR_BF_DESIGNACAO
FROM [dbo].[DIM_SECTOR_BF] D left join [stg].[tbl_O_SETOR] O ON D.DSC_SECTOR_BF=O.SETOR_BF
