
CREATE   VIEW [dbo].[VW_DIM_COMPETENCIA_ONET_DET] AS 
SELECT D.ID_DIM_COMPETENCIA_ONET_DET
	,D.DSC_COMPETENCIA_ONET_DET
	,O.TIPO_COMPETENCIA
	,O.COMPETENCIA_ONET_AGR
	,O.COMPETENCIA_ONET_AGR_DESIGNACAO
	,O.COMPETENCIA_ONET_DETALHADA
	,O.COMPETENCIA_ONET_DETALHADA_DESIG
	,O.COMPETENCIA_ONET_DETALHADA_DESC
	,O.ASSET
FROM [dbo].[DIM_COMPETENCIA_ONET_DET] D LEFT JOIN STG.[tbl_O_COMPETENCIAS_ONET] O ON D.ID_DIM_COMPETENCIA_ONET_DET=O.[competencia_onet_detalhada]
